export const ENV_KEY = {
  PORT: 'PORT',
  BD_URL: 'DB_URL',
  JWT_SECRET: 'JWT_SECRET',
  JWT_TOKEN_EXPIRATION_TIME: 'JWT_TOKEN_EXPIRATION_TIME',
  DB_HOST:'DB_HOST',
  DB_PORT:'DB_PORT',
  DB_PASSWORD:'DB_PASSWORD',
  DB_DATABASE:'DB_DATABASE',
  DB_USERNAME:'DB_USERNAME'
};

export const ERROR = {
  UNAUTHORIZED: 'UNAUTHORIZED',
  CATEGORY_NOT_FOUND: 'CATEGORY_NOT_FOUND',
  CATEGORY_ALREADY_EXISTS: 'CATEGORY_ALREADY_EXISTS',
  BLOG_NOT_FOUND: 'BLOG_NOT_FOUND'
}
